.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. oakcoin_qt test_oakcoin_qt
clean: FORCE
	$(MAKE) -C .. oakcoin_qt_clean test_oakcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_oakcoin_qt_check
oakcoin-qt oakcoin-qt.exe: FORCE
	 $(MAKE) -C .. oakcoin_qt
